//>>built
define("dojox/mobile/common","dojo/_base/array,dojo/_base/config,dojo/_base/connect,dojo/_base/lang,dojo/_base/window,dojo/_base/kernel,dojo/dom-class,dojo/dom-construct,dojo/ready,dojo/touch,dijit/registry,./sniff,./uacss".split(","),function(k,g,i,j,c,o,l,m,p,r,q,e){var a=j.getObject("dojox.mobile",!0);if("undefined"==typeof Liferay||null==Liferay)c.doc.dojoClick=!0;e.add("clicks-prevented",!(4.1<=e("android")));if(e("clicks-prevented"))a._sendClick=function(a,b){for(var f=a;f;f=f.parentNode)if(f.dojoClick)return;
f=c.doc.createEvent("MouseEvents");f.initMouseEvent("click",!0,!0,c.global,1,b.screenX,b.screenY,b.clientX,b.clientY);a.dispatchEvent(f)};a.getScreenSize=function(){return{h:c.global.innerHeight||c.doc.documentElement.clientHeight,w:c.global.innerWidth||c.doc.documentElement.clientWidth}};a.updateOrient=function(){var d=a.getScreenSize();l.replace(c.doc.documentElement,d.h>d.w?"dj_portrait":"dj_landscape",d.h>d.w?"dj_landscape":"dj_portrait")};a.updateOrient();a.tabletSize=500;a.detectScreenSize=
function(d){var b=a.getScreenSize(),f=Math.min(b.w,b.h),e,h;if(f>=a.tabletSize&&(d||!this._sz||this._sz<a.tabletSize))e="phone",h="tablet";else if(f<a.tabletSize&&(d||!this._sz||this._sz>=a.tabletSize))e="tablet",h="phone";h&&(l.replace(c.doc.documentElement,"dj_"+h,"dj_"+e),i.publish("/dojox/mobile/screenSize/"+h,[b]));this._sz=f};a.detectScreenSize();a.hideAddressBarWait="number"===typeof g.mblHideAddressBarWait?g.mblHideAddressBarWait:1500;a.hide_1=function(){scrollTo(0,1);a._hidingTimer=0==a._hidingTimer?
200:2*a._hidingTimer;setTimeout(function(){a.isAddressBarHidden()||a._hidingTimer>a.hideAddressBarWait?(a.resizeAll(),a._hiding=!1):setTimeout(a.hide_1,a._hidingTimer)},50)};a.hideAddressBar=function(){if(!a.disableHideAddressBar&&!a._hiding){a._hiding=!0;a._hidingTimer=e("ios")?200:0;var d=screen.availHeight;if(e("android")){d=outerHeight/devicePixelRatio;if(0==d)a._hiding=!1,setTimeout(function(){a.hideAddressBar()},200);d<=innerHeight&&(d=outerHeight);if(3>e("android"))c.doc.documentElement.style.overflow=
c.body().style.overflow="visible"}if(c.body().offsetHeight<d)c.body().style.minHeight=d+"px",a._resetMinHeight=!0;setTimeout(a.hide_1,a._hidingTimer)}};a.isAddressBarHidden=function(){return 1===pageYOffset};a.resizeAll=function(d,b){if(!a.disableResizeAll){i.publish("/dojox/mobile/resizeAll",[d,b]);i.publish("/dojox/mobile/beforeResizeAll",[d,b]);if(a._resetMinHeight)c.body().style.minHeight=a.getScreenSize().h+"px";a.updateOrient();a.detectScreenSize();var f=function(a){var b=a.getParent&&a.getParent();
return!(b&&b.resize||!a.resize)},e=function(a){k.forEach(a.getChildren(),function(a){f(a)&&a.resize();e(a)})};b?(b.resize&&b.resize(),e(b)):k.forEach(k.filter(q.toArray(),f),function(a){a.resize()});i.publish("/dojox/mobile/afterResizeAll",[d,b])}};a.openWindow=function(a,b){c.global.open(a,b||"_blank")};a._detectWindowsTheme=function(){navigator.userAgent.match(/IEMobile\/10\.0/)&&m.create("style",{innerHTML:"@-ms-viewport {width: auto !important}"},c.doc.head);var a=function(){l.add(c.doc.documentElement,
"windows_theme");o.experimental("Dojo Mobile Windows theme","Behavior and appearance of the Windows theme are experimental.")},b=e("windows-theme");if(void 0!==b)b&&a();else{for(var f,g=function(b){return b&&-1!==b.indexOf("/windows/")?(e.add("windows-theme",!0),a(),!0):!1},h=c.doc.styleSheets,b=0;b<h.length;b++)if(!h[b].href){var i=h[b].cssRules||h[b].imports;if(i)for(f=0;f<i.length;f++)if(g(i[f].href))return}f=c.doc.getElementsByTagName("link");for(b=0;b<f.length&&!g(f[b].href);b++);}};!1!==g.mblApplyPageStyles&&
l.add(c.doc.documentElement,"mobile");e("chrome")&&l.add(c.doc.documentElement,"dj_chrome");if(c.global._no_dojo_dm){var j=c.global._no_dojo_dm,n;for(n in j)a[n]=j[n];a.deviceTheme.setDm(a)}e.add("mblAndroidWorkaround",!1!==g.mblAndroidWorkaround&&3>e("android"),void 0,!0);e.add("mblAndroid3Workaround",!1!==g.mblAndroid3Workaround&&3<=e("android"),void 0,!0);a._detectWindowsTheme();p(function(){a.detectScreenSize(!0);l.add(c.body(),"mblBackground");!1!==g.mblAndroidWorkaroundButtonStyle&&e("android")&&
m.create("style",{innerHTML:"BUTTON,INPUT[type='button'],INPUT[type='submit'],INPUT[type='reset'],INPUT[type='file']::-webkit-file-upload-button{-webkit-appearance:none;} audio::-webkit-media-controls-play-button,video::-webkit-media-controls-play-button{-webkit-appearance:media-play-button;} video::-webkit-media-controls-fullscreen-button{-webkit-appearance:media-fullscreen-button;}"},c.doc.head,"first");e("mblAndroidWorkaround")&&m.create("style",{innerHTML:".mblView.mblAndroidWorkaround{position:absolute;top:-9999px !important;left:-9999px !important;}"},
c.doc.head,"last");var d=a.resizeAll;if(!1!==g.mblHideAddressBar&&-1!=navigator.appVersion.indexOf("Mobile")||!0===g.mblForceHideAddressBar)if(a.hideAddressBar(),!0===g.mblAlwaysHideAddressBar)d=a.hideAddressBar;var b=6<=e("ios");if((e("android")||b)&&void 0!==c.global.onorientationchange){var f=d,j,h,k;b?(h=c.doc.documentElement.clientWidth,k=c.doc.documentElement.clientHeight):(d=function(){var a=i.connect(null,"onresize",null,function(b){i.disconnect(a);f(b)})},j=a.getScreenSize());i.connect(null,
"onresize",null,function(e){if(b){var d=c.doc.documentElement.clientWidth,g=c.doc.documentElement.clientHeight;d==h&&g!=k&&f(e);h=d;k=g}else d=a.getScreenSize(),d.w==j.w&&100<=Math.abs(d.h-j.h)&&f(e),j=d})}i.connect(null,void 0!==c.global.onorientationchange?"onorientationchange":"onresize",null,d);c.body().style.visibility="visible"});return a});